project:
  type: website
  output-dir: _site

website:
  title: "vhs"
  repo-url: https://github.com/avkoehl/valley-floor
  repo-actions: [issue]
  navbar:
    right:
      - icon: github
        href: https://github.com/avkoehl/valley-floor
    left:
      - text: Home
        href: docs_source/index.qmd
      - text: Example
        href: docs_source/notebooks/example.ipynb
      - text: Reference
        href: docs_source/reference/index.qmd

quartodoc:
  package: vhs
  dir: docs_source/reference
  parser: google
  sections:
    - title: Core
      contents:
        - map_valley_floor
        - map_valley_floor_detailed
    - title: Inputs
      contents:
        - prepare_inputs
    - title: Configuration
      contents:
        - Parameters
        - ValleyFloorDetailed
