project:
  type: website
  output-dir: _site

website:
  title: "valley-floor"
  navbar:
    left:
      - file: docs_source/index.qmd
        text: Home
      - file: docs_source/notebooks/example.ipynb
        text: Example
      - file: docs_source/reference/index.qmd
        text: Reference

quartodoc:
  package: valley_floor
  dir: docs_source/reference
  parser: google
  sections:
    - title: Core
      contents:
        - delineate
        - delineate_from_dem_and_flowlines
    - title: Postprocessing
      contents:
        - postprocess
    - title: Inputs
      contents:
        - prepare_inputs
    - title: Parameters
      contents:
        - Parameters
        - PreprocessingParameters
        - PostprocessingParameters
