[project]
name = "vhs"
version = "0.1.0"
description = "Delineate valley floors from digital elevation models"
authors = [
    {name = "Arthur Koehl", email = "avkoehl@ucdavis.edu"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "geopandas>=1.1.1",
    "numpy>=2.0.0",
    "rioxarray>=0.19.0",
    "scikit-image>=0.25.0",
    "scipy>=1.16.0",
    "shapelysmooth>=0.2.1",
    "xarray>=2025.1.0",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
    "matplotlib>=3.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
