name: Publish Docs
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: uv sync --group dev
      - run: uv run quartodoc build
      - run: quarto publish gh-pages --no-prompt
